config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'comments/new'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "pages#home"

  resources :plats do
    resources :comments, only: [:new, :create]
  end
  resources :comments, only: [:destroy]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :plat

  validates :avis, presence: true
end

app/models/plat.rb
class Plat < ApplicationRecord
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_plat, only: %i[new create]

  def new
    @comment = Comment.new
  end


  def create
    @comment = Comment.new(comment_params)
    @comment.plat = @plat
    if @comment.save
      redirect_to plat_path(@plat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to plat_path(@comment.plat), status: :see_other
  end



  private

  def set_plat
    @plat = Plat.find(params[:plat_id])
  end

  def comment_params
    params.require(:comment).permit(:avis)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

end

app/controllers/plats_controller.rb
class PlatsController < ApplicationController
  def index
    @plats = Plat.all
  end

  def show
    @plat = Plat.find(params[:id])
  end

  def new
    @plat = Plat.new
  end

  def create
    @plat = Plat.new(plats_params)
    if @plat.save
      redirect_to plats_path(@spot)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @plat = Plat.find(params[:id])
  end

  def update
    @plat = Plat.find(params[:id])
    @plat.update(params[:plat])
    redirect_to plat_path(@plat)
  end

  def destroy
    @plat = Plat.find(params[:id])
    @plat.destroy
    redirect_to plats_path, status: :see_other
  end

  private

  def plats_params
    params.require(:plat).permit(:nom, :categorie, :ingredients, :image, :prix)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plats_helper.rb
module PlatsHelper
end

app/views/comments/new.html.erb
<div class="position-button">
  <a href="<%= plat_path(@plat) %>" class="button-return"><i class="fa-regular fa-circle-left"></i> <b>Retour</b></a>
</div>

  <div class="align-center">
  <h2 class="font-title-comment"><b>Nouveau commentaire</b></h2>
  <br>
    <%= simple_form_for [@plat, @comment] do |f| %>
      <%= f.input :avis, :as => :text %>
      <%= f.input :note %>
      <%= f.input :picture %>
      <%= f.submit "Validation", class: "btn btn-primary" %>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CookerOps</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>

        <%= yield %>

    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="align-center">
  <h1><strong>Chez COOKER OPS</strong></h1>
  <p>Découvrez les spécialités culinaires du monde</p>
  <a class="btn btn-warning" href="<%= plats_path %>"><b>Voir le menu</b></a>
</div>

app/views/plats/edit.html.erb
<%= form_with model: @plat do |f| %>
  <%= f.label :nom %>
  <%= f.text_field :nom %>
  <%= f.label :categorie %>
  <%= f.text_field :categorie %>
    <%= f.label :ingredients %>
  <%= f.text_field :ingredients %>
    <%= f.label :description %>
  <%= f.text_field :description %>
    <%= f.label :image %>
  <%= f.text_field :image %>
  <%= f.label :prix %>
  <%= f.number_field :prix %>
  <%= f.submit %>
<% end %>

app/views/plats/index.html.erb
<div class="position-button">
  <a href="<%= root_path %>" class="button-return"><i class="fa-regular fa-circle-left"></i> <b>Retour</b></a>
</div>



<div class="container list-menu">
  <div class="title-position">
    <h1 class="font-title"><b>Le menu</b></h1>
  </div>

  <div class="row padding-bottom">
  <% @plats.each do |plat| %>
    <div class="d-flex justify-content-between col-sm-6 col-md-4 col-lg-3 mb-4">

      <div class="card" style="width: 18rem;">
        <img src="<%= plat.image %>" class="card-img-top plat-<%= plat.id %>", alt="plat-<%= plat.id %>">
        <div class="card-body">
          <h5 class="card-title"><%= plat.nom %></h5>
          <p class="card-text"><%= plat.prix %>€</p>
        <a href="<%= plat_path(plat) %>" class="btn btn-warning"><b>En savoir plus</b></a>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/plats/new.html.erb
<div><%= link_to "retour au menu", plats_path %></div>

<%= form_with model: @plat do |f| %>
  <%= f.label :nom %>
  <%= f.text_field :nom %>
  <%= f.label :categorie %>
  <%= f.text_field :categorie %>
    <%= f.label :ingredients %>
  <%= f.text_field :ingredients %>
    <%= f.label :description %>
  <%= f.text_field :description %>
    <%= f.label :image %>
  <%= f.text_field :image %>
  <%= f.label :prix %>
  <%= f.number_field :prix %>
  <%= f.submit %>
<% end %>

app/views/plats/show.html.erb
<div class="position-button">
  <a href="<%= plats_path %>" class="button-return"><i class="fa-regular fa-circle-left"></i> <b>Retour</b></a>
</div>

<div class= "container list-menu">
  <br>
  <h1 class="font-title text-center pb-2"><b>Le plat</b></h1>
  <div class="container bg-white p-4 rounded">
    <div class= "row justify-content-center">
      <div class= "col-12 col-md-6 text-center">
          <h2 class="text-uppercase"><b><%= @plat.nom %></b></h2>
          <p><b>CATEGORIE :</b> <%= @plat.categorie %></p>
          <p><b>INGREDIENTS :</b> <%= @plat.ingredients %></p>
          <p><b>DESCRIPTION :</b> <%= @plat.description %></p>
          <p><b>PRIX :</b> <%= @plat.prix %> €</p>
        </div>

        <div class= "col-12 col-md-6">
          <img src="<%= @plat.image %>" class="illustration">
        </div>
    </div>
  </div>

  <h2 class="font-title text-center pt-4"><strong>Commentaires</strong></h2>
  <div class="position-center">
    <a href="<%= new_plat_comment_path(@plat) %>" class="button-comment">Ajouter un commentaire</a>
  </div>
<div class="container list-group">
    <% @plat.comments.each do |comment| %>
    <div class="box-commentaire">
        <div>A propos du plat: <b><%= @plat.nom %></b></div>
        <div>Avis: <%= comment.avis %></div>
        <div>Note: <%= comment.note.to_i %>/20</div>
        <div><%= link_to "Delete",
            comment_path(comment),
            data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
        %></div>



    </div>
  <% end %>
</div>

</div>

app/views/shared/_footer.html.erb
<div class="footer">
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
    </div>

    <div class="col-md-6">
      <div class="footer-copyright">
        This footer is made with <i class="fas fa-heart"></i> at Le Wagon
      </div>
    </div>
  </div>
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <h5><i class="fa-regular fa-lemon"></i> Cooker Ops</h5>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
              <% link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>